name: Build workflow
on:
  workflow_dispatch:
    inputs:
      exampleInput:
        description: 'Example field'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk build //:hello
      - uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: bazel-bin/hello_/hello
          output_path: hello.provenance
        continue-on-error: true
      - uses: actions/upload-artifact@v2
        with:
          path: |
            bazel-bin/hello_/hello
            hello.provenance

  call-workflow:
    uses: MarkLodato/example-reusable-workflow/.github/workflows/reusable.yaml@main
