name: Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: ls /imagegeneration; find /imagegeneration -type f -printf "\n%p\n" -exec cat {} \;
